-- Create databases
CREATE DATABASE IF NOT EXISTS tpch;

-- Create tables
DROP TABLE IF EXISTS tpch.nation;
CREATE EXTERNAL TABLE tpch.nation (
  N_NATIONKEY SMALLINT,
  N_NAME STRING,
  N_REGIONKEY SMALLINT,
  N_COMMENT STRING)
ROW FORMAT DELIMITED FIELDS TERMINATED BY '|'
STORED AS TEXTFILE
LOCATION '/test-warehouse/tpch.nation';
